name: Issue check

on:
  issues:
    types:
      - edited
      - closed
      - reopened

# Allow GITHUB_TOKEN to write to issues
permissions:
  issues: write

jobs:
  qw-check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    outputs:
      # problems found in parsing the issue metadata (currently hardcoded to true)
      issues: ${{ steps.qw.outputs.issues }}
      # existing comment on the pull request
      comment-id: ${{ steps.fc.outputs.comment-id }}
    steps:
      - name: Checkout qw
        uses: actions/checkout@v3
        with:
          repository: UCL-ARC/qw
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: pip install .
      - name: qw check
        # always set to true so it runs
        id: qw
        run: |
          echo '## Problems found from last edit by {{ .user }} on {{ .date | date "2006-01-02"}}' > issue-header.md &&
          echo "" >> issue-header.md  &&
          echo "- [ ] First issue details" >> issues.md  &&
          echo "- [ ] Second Issue details" >> issues.md  &&
          echo "- [ ] Third issue" >> issues.md  &&
          touch empty.md &&
          mkdir qw &&
          cat issue-header.md issues.md > qw/issues.md &&
          if [-s empty.md] && echo "issues=true" >> "$GITHUB_OUTPUT" || echo "issues=" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@master
        with:
          name: qw
          path: qw
      - name: Find Comment
        # has output "comment-id"
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number:  ${{ github.event.issue.number }}
          comment-author: "github-actions[bot]"
          body-includes: "## Problems found from last edit"
      - name: Dump GitHub output
        run: |
          cat "$GITHUB_OUTPUT"

  comment-problems:
    runs-on: ubuntu-latest
    needs: qw-check
    if: ${{ needs.qw-check.outputs.issues != '' }}
    steps:
      - name: Dump GitHub needs
        env:
          GITHUB_NEEDS: ${{ toJson(needs) }}
        run: |
          echo "$GITHUB_NEEDS"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: dump outputs
        run: |
          echo "${{ needs.qw-check.outputs.issues}}"
      - uses: actions/download-artifact@master
        with:
          name: qw
          path: qw
      - name: dump issue file
        run: |
          cat qw/issues.md
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.8
        with:
          template: qw/issues.md
          vars: |
            user: ${{ github.actor }}
            date: ${{ github.event.issue.updated_at }}
      - name: Create Comment
        if: needs.qw-check.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.template.outputs.result }}
      - name: Update Comment
        if: needs.qw-check.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          comment-id: ${{ needs.qw-check.outputs.comment-id }}
          body: ${{ steps.template.outputs.result }}
          edit-mode: replace

  comment-fixed:
    runs-on: ubuntu-latest
    needs: qw-check
    if: ${{ needs.qw-check.outputs.issues == '' && needs.qw-check.outputs.comment-id != '' }}
    steps:
      - name: Dump GitHub needs
        env:
          GITHUB_NEEDS: ${{ toJson(needs) }}
        run: |
          echo "$GITHUB_NEEDS"
      - name: Create resolved issues markdown file
        run: |
          mkdir qw &&
          echo '## Problems fixed from edit by {{ .user }} on {{ .date | date "2006-01-02"}}' > qw/issues.md
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.8
        with:
          template: qw/issues.md
          vars: |
            user: ${{ github.actor }}
            date: ${{ github.event.issue.updated_at }}
      - name: Update Comment
        if: needs.qw-check.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          comment-id: ${{ needs.qw-check.outputs.comment-id }}
          body: ${{ steps.template.outputs.result }}
          edit-mode: replace