name: Issue check

on:
  issues:
    types:
      - edited
      - closed
      - reopened

# Allow GITHUB_TOKEN to write to issues
permissions:
  issues: write

jobs:
  qw_check:
    if: ${{ github.event_name != 'pull_request' }}
    outputs:
      issues: ${{ steps.qw-check.output.issues }}
      comment: ${{ steps.qw-check.output.comment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout qw
        uses: actions/checkout@v2
        with:
          repository: UCL-ARC/qw
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: pip install .
      - name: qw check
        # always set to true so it runs
        id: qw-check
        run: |
          echo "comment=true" >> "$GITHUB_OUTPUT" &&
          echo "- First issue details\n- Second Issue details\n- Third issue" > issues.md
      - uses: actions/upload-artifact@master
        with:
          name: issues
          path: issues.md

  comment:
    runs-on: ubuntu-latest
    needs: qw_check
    if: ${{ needs.qw_check.outputs.comment }} == 'true'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: dump outputs
        run: |
          echo "${{ needs.qw_check.outputs.comment }}"
      - uses: actions/download-artifact@master
        with:
          name: issues
          path: qw/issues.md
      - name: dump issue file
        run: |
          cat qw/issues.md
      - name: Comment
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body-path: qw/issues.md
