name: QW Check PR
# Checks to see if a PR can be parsed by qw, and any outstanding problems with it.
# If problems are found, the action will fail and give an error message of the problems found

on:
  pull_request:
    paths-ignore:
      - "**.md"


jobs:
  qw-check-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout qw
        uses: actions/checkout@v3
        with:
          repository: UCL-ARC/qw
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: pip install .
      - name: qw check
        id: qw
        if : ${{ !contains(github.event.pull_request.labels.*.name, 'qw-ignore') }}
        run: |
          qw check --issue ${{ github.event.issue.number }}  --repository ${{ github.repository }}
      - name: skip qw check
        id: skip
        if : ${{ contains(github.event.pull_request.labels.*.name, 'qw-ignore') }}
        run: echo "Ignored by qw"
